version: 2

project_name: remotesearch

before:
  hooks:
    - go mod tidy

builds:
  - id: remotesearch
    main: ./cmd/search
    binary: remotesearch
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

brews:
  - name: remotesearch
    repository:
      owner: vosiander
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/vosiander/remote-search"
    description: "SSH into multiple hosts in parallel and search for files"
    license: "MIT"
    install: |
      bin.install "remotesearch"
    test: |
      system "#{bin}/remotesearch", "--version"

release:
  github:
    owner: vosiander
    name: remote-search
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
