version: '3'

vars:
  BINARY_NAME: hostsearch
  BUILD_DIR: ./cmd/search

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list

  build:
    desc: Build the hostsearch binary
    cmds:
      - go build -o {{.BINARY_NAME}} {{.BUILD_DIR}}
    sources:
      - "{{.BUILD_DIR}}/**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_NAME}}"

  run:
    desc: Build and run the hostsearch application (usage task run -- -c config.yaml --all "*.mp3")
    deps:
      - build
    cmds:
      - ./{{.BINARY_NAME}} {{.CLI_ARGS}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint (if installed)
    cmds:
      - golangci-lint run
    preconditions:
      - sh: command -v golangci-lint
        msg: "golangci-lint is not installed"

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy
